<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<ApplicationIcon>icon.ico</ApplicationIcon>
		<AssemblyVersion>1.1.1.0</AssemblyVersion>
		<AssemblyName>ProtocoLab</AssemblyName>
		<Copyright>Insightec 2024</Copyright>
		<PackageIcon>icon.ico</PackageIcon>
		<FileVersion>1.0.6.0</FileVersion>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Version>1.1.1.0</Version>
		<Authors>Rotem Geva</Authors>
	</PropertyGroup>

	<ItemGroup>
	  <Content Include="icon.ico" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="..\icon.ico">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	  <None Include="..\README.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="CsvHelper" Version="33.0.1" />
		<PackageReference Include="Serilog" Version="4.0.0" />
		<PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
		<PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
		<PackageReference Include="Prism.Wpf" Version="9.0.401-pre" />
		<PackageReference Include="Prism.DryIoc" Version="9.0.401-pre" />
		<PackageReference Include="SharpZipLib" Version="1.4.2" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\CompareCli\CompareCli.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <None Update="icon.ico">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

</Project>
